"""
model_diagnostics.py

Run post-estimation diagnostics for GARCH-family models in the 2008 mortgage
crisis volatility project.

This script reads standardized residuals generated by garch_models.py and checks
whether the fitted volatility models have removed the main dependence patterns in
returns and squared returns.

Expected input:
    outputs/models/garch/standardized_residuals.csv

Main outputs:
    outputs/tables/garch_diagnostics/post_model_diagnostics.csv
    outputs/tables/garch_diagnostics/model_diagnostics_summary.txt

Run:
    python src/model_diagnostics.py

Required packages:
    pip install pandas numpy scipy statsmodels
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List, Optional

import numpy as np
import pandas as pd
from scipy.stats import jarque_bera
from statsmodels.regression.linear_model import OLS
from statsmodels.stats.diagnostic import acorr_ljungbox, het_arch
from statsmodels.tools.tools import add_constant


# -----------------------------------------------------------------------------
# Project paths
# -----------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[1]
RESIDUAL_PATH = PROJECT_ROOT / "outputs" / "models" / "garch" / "standardized_residuals.csv"
TABLE_DIR = PROJECT_ROOT / "outputs" / "tables" / "garch_diagnostics"


# -----------------------------------------------------------------------------
# Settings
# -----------------------------------------------------------------------------

LJUNG_BOX_LAGS = [10, 20]
ARCH_LM_LAG = 10
MIN_OBS = 100
SIGNIFICANCE_LEVEL = 0.05

MODEL_ORDER = ["GARCH_11", "GJR_GARCH_11", "EGARCH_11"]
PERIOD_ORDER = ["full_sample", "pre_crisis", "crisis", "post_crisis"]
ASSET_ORDER = ["SPY", "XLF", "KBE"]


# -----------------------------------------------------------------------------
# IO helpers
# -----------------------------------------------------------------------------

def ensure_output_dir() -> None:
    """Create output directory if it does not exist."""
    TABLE_DIR.mkdir(parents=True, exist_ok=True)


def load_standardized_residuals(path: Path = RESIDUAL_PATH) -> pd.DataFrame:
    """Load standardized residuals produced by garch_models.py."""
    if not path.exists():
        raise FileNotFoundError(
            f"Could not find {path}. Run garch_models.py before model_diagnostics.py."
        )

    df = pd.read_csv(path, parse_dates=["date"])
    required = {
        "date",
        "asset",
        "period",
        "model",
        "standardized_residual",
        "squared_standardized_residual",
    }
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(
            f"Missing required columns in {path}: {sorted(missing)}. "
            f"Available columns: {list(df.columns)}"
        )

    df = df.sort_values(["asset", "period", "model", "date"]).reset_index(drop=True)
    df["standardized_residual"] = pd.to_numeric(df["standardized_residual"], errors="coerce")
    df["squared_standardized_residual"] = pd.to_numeric(
        df["squared_standardized_residual"], errors="coerce"
    )
    return df


# -----------------------------------------------------------------------------
# Diagnostic tests
# -----------------------------------------------------------------------------

def _safe_ljungbox_pvalue(series: pd.Series, lag: int) -> float:
    """Return Ljung-Box p-value at a given lag, or NaN if unavailable."""
    clean = pd.Series(series).replace([np.inf, -np.inf], np.nan).dropna()
    if clean.shape[0] <= lag + 5:
        return np.nan

    try:
        result = acorr_ljungbox(clean, lags=[lag], return_df=True)
        return float(result["lb_pvalue"].iloc[0])
    except Exception:
        return np.nan


def _safe_arch_lm_pvalue(series: pd.Series, nlags: int = ARCH_LM_LAG) -> float:
    """Return ARCH-LM p-value, or NaN if unavailable."""
    clean = pd.Series(series).replace([np.inf, -np.inf], np.nan).dropna()
    if clean.shape[0] <= nlags + 5:
        return np.nan

    try:
        _, pvalue, _, _ = het_arch(clean, nlags=nlags)
        return float(pvalue)
    except Exception:
        return np.nan


def _safe_jarque_bera(series: pd.Series) -> Dict[str, float]:
    """Return Jarque-Bera statistic and p-value."""
    clean = pd.Series(series).replace([np.inf, -np.inf], np.nan).dropna()
    if clean.shape[0] < MIN_OBS:
        return {"jb_stat": np.nan, "jb_pvalue": np.nan}

    try:
        stat, pvalue = jarque_bera(clean)
        return {"jb_stat": float(stat), "jb_pvalue": float(pvalue)}
    except Exception:
        return {"jb_stat": np.nan, "jb_pvalue": np.nan}


def _safe_sign_bias_test(std_resid: pd.Series) -> Dict[str, float]:
    """Run a simple sign-bias test on standardized residuals.

    The test regression is:
        z_t^2 = c + b * I(z_{t-1} < 0) + u_t

    A small p-value for b suggests remaining sign asymmetry in the standardized
    residuals. If GJR-GARCH removes sign bias better than GARCH, this supports
    the asymmetric volatility specification.
    """
    z = pd.Series(std_resid).replace([np.inf, -np.inf], np.nan).dropna()
    if z.shape[0] < MIN_OBS:
        return {"sign_bias_coef": np.nan, "sign_bias_pvalue": np.nan}

    y = np.square(z).iloc[1:].reset_index(drop=True)
    sign_dummy = (z.shift(1).iloc[1:] < 0).astype(float).reset_index(drop=True)

    if sign_dummy.nunique() < 2:
        return {"sign_bias_coef": np.nan, "sign_bias_pvalue": np.nan}

    try:
        x = add_constant(sign_dummy, has_constant="add")
        model = OLS(y, x, missing="drop").fit()
        return {
            "sign_bias_coef": float(model.params.iloc[1]),
            "sign_bias_pvalue": float(model.pvalues.iloc[1]),
        }
    except Exception:
        return {"sign_bias_coef": np.nan, "sign_bias_pvalue": np.nan}


def _safe_engle_ng_joint_test(std_resid: pd.Series) -> Dict[str, float]:
    """Run an Engle-Ng style joint sign and size bias test.

    The auxiliary regression is:
        z_t^2 = c
                + b1 * I(z_{t-1} < 0)
                + b2 * I(z_{t-1} < 0) * z_{t-1}
                + b3 * I(z_{t-1} >= 0) * z_{t-1}
                + u_t

    The reported p-value is from a joint F-test that b1=b2=b3=0.
    """
    z = pd.Series(std_resid).replace([np.inf, -np.inf], np.nan).dropna()
    if z.shape[0] < MIN_OBS:
        return {"engle_ng_joint_pvalue": np.nan}

    z_lag = z.shift(1).iloc[1:].reset_index(drop=True)
    y = np.square(z).iloc[1:].reset_index(drop=True)

    neg = (z_lag < 0).astype(float)
    pos = 1.0 - neg

    x = pd.DataFrame(
        {
            "sign_bias": neg,
            "negative_size_bias": neg * z_lag,
            "positive_size_bias": pos * z_lag,
        }
    )

    # If regressors are degenerate, skip the test.
    if x.nunique().min() < 2:
        return {"engle_ng_joint_pvalue": np.nan}

    try:
        x = add_constant(x, has_constant="add")
        model = OLS(y, x, missing="drop").fit()
        f_test = model.f_test("sign_bias = 0, negative_size_bias = 0, positive_size_bias = 0")
        return {"engle_ng_joint_pvalue": float(f_test.pvalue)}
    except Exception:
        return {"engle_ng_joint_pvalue": np.nan}


def _flag_from_pvalue(pvalue: float, reject_label: str = "yes", nonreject_label: str = "no") -> str:
    """Convert a p-value into a yes/no flag using the global significance level."""
    if pd.isna(pvalue):
        return "not_available"
    return reject_label if pvalue < SIGNIFICANCE_LEVEL else nonreject_label


# -----------------------------------------------------------------------------
# Row-level diagnostic extraction
# -----------------------------------------------------------------------------

def run_diagnostics_for_group(group: pd.DataFrame) -> Dict[str, object]:
    """Run diagnostics for one asset-period-model group."""
    asset = group["asset"].iloc[0]
    period = group["period"].iloc[0]
    model_name = group["model"].iloc[0]

    z = group["standardized_residual"].replace([np.inf, -np.inf], np.nan).dropna()
    z2 = np.square(z)

    row: Dict[str, object] = {
        "asset": asset,
        "period": period,
        "model": model_name,
        "n_obs": int(z.shape[0]),
    }

    # Ljung-Box diagnostics.
    for lag in LJUNG_BOX_LAGS:
        row[f"lb_resid_pvalue_lag_{lag}"] = _safe_ljungbox_pvalue(z, lag)
        row[f"lb_squared_resid_pvalue_lag_{lag}"] = _safe_ljungbox_pvalue(z2, lag)

    # ARCH-LM and normality diagnostics.
    row[f"arch_lm_pvalue_lag_{ARCH_LM_LAG}"] = _safe_arch_lm_pvalue(z, ARCH_LM_LAG)
    row.update(_safe_jarque_bera(z))

    # Sign-bias diagnostics.
    row.update(_safe_sign_bias_test(z))
    row.update(_safe_engle_ng_joint_test(z))

    # Compact interpretation flags.
    resid_lb_pvalues = [row[f"lb_resid_pvalue_lag_{lag}"] for lag in LJUNG_BOX_LAGS]
    squared_lb_pvalues = [row[f"lb_squared_resid_pvalue_lag_{lag}"] for lag in LJUNG_BOX_LAGS]

    min_resid_lb = np.nanmin(resid_lb_pvalues) if not all(pd.isna(x) for x in resid_lb_pvalues) else np.nan
    min_squared_lb = (
        np.nanmin(squared_lb_pvalues) if not all(pd.isna(x) for x in squared_lb_pvalues) else np.nan
    )

    row["remaining_residual_autocorrelation"] = _flag_from_pvalue(min_resid_lb)
    row["remaining_squared_residual_autocorrelation"] = _flag_from_pvalue(min_squared_lb)
    row["remaining_arch_effect"] = _flag_from_pvalue(row[f"arch_lm_pvalue_lag_{ARCH_LM_LAG}"])
    row["non_normal_standardized_residuals"] = _flag_from_pvalue(row["jb_pvalue"])
    row["remaining_simple_sign_bias"] = _flag_from_pvalue(row["sign_bias_pvalue"])
    row["remaining_engle_ng_bias"] = _flag_from_pvalue(row["engle_ng_joint_pvalue"])

    # A simple adequacy score: larger is better. Normality is not included because
    # heavy tails often remain in financial returns even after GARCH filtering.
    checks = [
        row["remaining_residual_autocorrelation"] == "no",
        row["remaining_squared_residual_autocorrelation"] == "no",
        row["remaining_arch_effect"] == "no",
        row["remaining_simple_sign_bias"] == "no",
        row["remaining_engle_ng_bias"] == "no",
    ]
    row["diagnostic_pass_count"] = int(sum(checks))
    row["diagnostic_total_count"] = int(len(checks))

    return row


def run_all_diagnostics(residuals: pd.DataFrame) -> pd.DataFrame:
    """Run diagnostics for all asset-period-model groups."""
    rows: List[Dict[str, object]] = []
    group_cols = ["asset", "period", "model"]

    for _, group in residuals.groupby(group_cols, sort=False):
        if group.shape[0] < MIN_OBS:
            continue
        rows.append(run_diagnostics_for_group(group))

    out = pd.DataFrame(rows)

    # Sort for readability.
    if not out.empty:
        out["asset"] = pd.Categorical(out["asset"], categories=ASSET_ORDER, ordered=True)
        out["period"] = pd.Categorical(out["period"], categories=PERIOD_ORDER, ordered=True)
        out["model"] = pd.Categorical(out["model"], categories=MODEL_ORDER, ordered=True)
        out = out.sort_values(["asset", "period", "model"]).reset_index(drop=True)
        out["asset"] = out["asset"].astype(str)
        out["period"] = out["period"].astype(str)
        out["model"] = out["model"].astype(str)

    return out


# -----------------------------------------------------------------------------
# Summary generation
# -----------------------------------------------------------------------------

def _format_pvalue(value: float) -> str:
    if pd.isna(value):
        return "NA"
    if value < 1e-4:
        return f"{value:.2e}"
    return f"{value:.4f}"


def create_summary(diagnostics: pd.DataFrame, path: Path) -> None:
    """Write a compact text summary of post-model diagnostics."""
    lines: List[str] = []
    lines.append("Post-GARCH diagnostic summary")
    lines.append("=============================")
    lines.append("")
    lines.append("Purpose:")
    lines.append(
        "These diagnostics evaluate whether the fitted GARCH-family models removed "
        "serial dependence, remaining ARCH effects, and sign asymmetry from standardized residuals."
    )
    lines.append("")
    lines.append("Main reading rules:")
    lines.append("- Ljung-Box residual p-value < 0.05 suggests remaining serial correlation.")
    lines.append("- Ljung-Box squared residual p-value < 0.05 suggests remaining volatility clustering.")
    lines.append("- ARCH-LM p-value < 0.05 suggests remaining conditional heteroskedasticity.")
    lines.append("- Jarque-Bera p-value < 0.05 suggests non-normal standardized residuals.")
    lines.append("- Sign-bias p-value < 0.05 suggests remaining asymmetric response to shocks.")
    lines.append("- Normality rejection is not treated as model failure by itself in financial returns.")
    lines.append("")

    if diagnostics.empty:
        lines.append("No diagnostics were produced.")
        path.write_text("\n".join(lines), encoding="utf-8")
        return

    lines.append(f"Diagnostic rows: {len(diagnostics)}")
    lines.append("")

    # Count flags by model.
    lines.append("Remaining ARCH effects by model:")
    for model_name, group in diagnostics.groupby("model"):
        count = int((group["remaining_arch_effect"] == "yes").sum())
        total = int(group.shape[0])
        lines.append(f"- {model_name}: {count}/{total} cases")
    lines.append("")

    lines.append("Remaining squared-residual autocorrelation by model:")
    for model_name, group in diagnostics.groupby("model"):
        count = int((group["remaining_squared_residual_autocorrelation"] == "yes").sum())
        total = int(group.shape[0])
        lines.append(f"- {model_name}: {count}/{total} cases")
    lines.append("")

    lines.append("Remaining sign bias by model:")
    for model_name, group in diagnostics.groupby("model"):
        count = int((group["remaining_simple_sign_bias"] == "yes").sum())
        total = int(group.shape[0])
        lines.append(f"- {model_name}: {count}/{total} cases")
    lines.append("")

    # Best diagnostic score by asset-period.
    lines.append("Best diagnostic pass count by asset and period:")
    for (asset, period), group in diagnostics.groupby(["asset", "period"]):
        best = group.loc[group["diagnostic_pass_count"].idxmax()]
        lines.append(
            f"- {asset} | {period}: {best['model']} "
            f"({int(best['diagnostic_pass_count'])}/{int(best['diagnostic_total_count'])} checks passed)"
        )
    lines.append("")

    # Crisis-period focus.
    crisis = diagnostics[diagnostics["period"] == "crisis"].copy()
    if not crisis.empty:
        lines.append("Crisis-period diagnostic highlights:")
        for _, row in crisis.sort_values(["asset", "model"]).iterrows():
            lines.append(
                f"- {row['asset']} | {row['model']}: "
                f"LB(z^2,20) p={_format_pvalue(row['lb_squared_resid_pvalue_lag_20'])}, "
                f"ARCH-LM p={_format_pvalue(row[f'arch_lm_pvalue_lag_{ARCH_LM_LAG}'])}, "
                f"sign-bias p={_format_pvalue(row['sign_bias_pvalue'])}, "
                f"score={int(row['diagnostic_pass_count'])}/{int(row['diagnostic_total_count'])}"
            )
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


# -----------------------------------------------------------------------------
# Main execution
# -----------------------------------------------------------------------------

def run() -> None:
    """Run the post-GARCH diagnostic pipeline."""
    ensure_output_dir()
    residuals = load_standardized_residuals()
    diagnostics = run_all_diagnostics(residuals)

    diagnostics_path = TABLE_DIR / "post_model_diagnostics.csv"
    summary_path = TABLE_DIR / "model_diagnostics_summary.txt"

    diagnostics.to_csv(diagnostics_path, index=False)
    create_summary(diagnostics, summary_path)

    print("Post-GARCH diagnostics completed.")
    print(f"Diagnostics table: {diagnostics_path}")
    print(f"Summary:           {summary_path}")


if __name__ == "__main__":
    run()
